import { Footer } from '@/components/Footer'
import './globals.scss'
import type { Metadata } from 'next'
import { Exo_2, Nunito } from 'next/font/google'

const exo2 = Exo_2({ subsets: ['latin'], variable:"--font-exo2" })
const nunito = Nunito({ subsets: ['latin'], variable:"--font-nunito" })

export const metadata: Metadata = {
  title: 'Rafael Simionato | Desenvolvedor Web Front-end & UI Designer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${exo2.variable} ${nunito.variable}`}>
        <div className='mainContainer'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
